### ISSUE TITLE
Retrieving items fails when items DO exist

### ISSUE THREAD

**Issue by mantazzo** [Nemirtingas/games-infos#1]
APPID: 365960

The steam_retriever fails to retrieve the item list for the game. Strangely enough, one of your older apps (SmartGoldbergEmu) did receive items correctly, so no idea what's the problem here (as the error I get is the Exception "failed (no items?)" and it's not really descriptive...).

**Comment by Nemirtingas** [comment]
Yup, fixed this.
My bad, I pushed a change in the items filename just after the test. Its fixed now, I'm moving to gitlab for the auto-build system.
https://gitlab.com/Nemirtingas/games-infos
