### ISSUE TITLE
Any solution?

### ISSUE THREAD

**Issue by TheMrMarcks** [Nemirtingas/games-infos#5]
Error while parsing AppID 1637140: The SSL connection could not be established, see inner exception. Authentication failed, see inner exception.
PD: it doesnt download the archivements or any image, only the game/dlc info, even using the api key.

**Comment by Nemirtingas** [comment]
No issues on my end for appid 1637140.
```
Got 1 AppIDs to check
 + Trying to get infos on 1637140...
   + Downloading background image
  + Trying to retrieve items...
  + No items exist for this AppID
  + Trying to retrieve achievements and stats...
  + Writing Achievements english.db_achievements.json
  + Achievements and stats were successfully generated!
  \ Type game, AppID 1637140, appName Fishards
```

**Comment by Nemirtingas** [comment]
Might be because you are using an old version of SSL. You might need to update openssl on Linux/MacOS and update Windows for newer SSL support.

**Comment by TheMrMarcks** [comment]
> openssl

So in order to fix it i need to install at least Windows 10 to fix it? im using an old machine; there isn't another workaround?

**Comment by Nemirtingas** [comment]
I have no way to modify the C# interpreter. If your OS doesn't support TLS v1.3, I can't do anything on the application side.
