### ISSUE TITLE
I can't edit the language or download the images

### ISSUE THREAD

**Issue by Com3Carne** [Nemirtingas/games-infos#8]
This is the command I am using: `.\steam_retriever.exe '1637140' -u 'username' -p 'password' -i -o 'Goldberg Emu' -l 'brazilian'`
Am I doing something wrong? Note: is it necessary to use apikey?

**Comment by Nemirtingas** [comment]
The language switch is only used if you use the api key instead of login with a steam account.
The api key is needed if you don't use a steam account.
If you use a steam account, you can't provide a language as it should be able to download all languages at the same time.

**Comment by Com3Carne** [comment]
> The language switch is only used if you use the api key instead of login with a steam account.
> The api key is needed if you don't use a steam account.
> If you use a steam account, you can't provide a language as it should be able to download all languages at the same time.

I understood.  However, I can't get my apikey to work.  He just ignores her.  Could you tell me where I'm going wrong?

**Comment by Nemirtingas** [comment]
I'm wrong. In the newer version you have to use a Steam account. The webapi key will be used only if the app can't read the stats/achievements schema and use the web api instead of Steam's network.

**Comment by Com3Carne** [comment]
> I'm wrong. In the newer version you have to use a Steam account. The webapi key will be used only if the app can't read the stats/achievements schema and use the web api instead of Steam's network.

So there is no possibility to get only my language?  Will all languages ​​always come?

**Comment by Nemirtingas** [comment]
Your language will be in the list if available. If you need only your language, you can still filter the results to match your needs.

**Comment by Com3Carne** [comment]
I got it.  But at the time, even if I put **-l **brazilian, all languages ​​appear.
If possible.  Could you pass me the command line to get only my language?

**Comment by Nemirtingas** [comment]
The goal of this project is to dump all possible informations, not to filter them. The language is only used by the web api as a fallback. There is currently no way in this app to get only the specified language.
