### ISSUE TITLE
Add macos sonoma support

### ISSUE THREAD

**Issue by iiasceri** [Nemirtingas/games-infos#9]
1) Nihao )
2) https://gitlab.com/1101839859/nemirtingas-steam-emu-unless
3) https://nnmclub.to/forum/viewtopic.php?t=1637220
4) https://appstorrent.ru/2348-no-mans-sky.html
5) На M1 Sonoma beta 1 - не работает(

Если зайти внутрь и запустить, то вот такие ошибки...
2023-06-06 23:35:43.245 No Man's Sky[29342:593448] cTkSystem mbIsCaptureEnabled: false
[S_API FAIL] SteamAPI_Init() failed; ipcserver GetSteamPath failed.
[S_API] SteamAPI_Init(): SteamAPI_IsSteamRunning() did not locate a running instance of Steam.
[S_API] SteamAPI_Init(): Could not determine Steam client install directory.

**Comment by Nemirtingas** [comment]
I don't know what you want here but it doesn't seem related to this repository.
